version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    platform: linux/amd64
    ports:
      - 5444:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  vault:
    image: vault:1.13.3
    restart: always
    ports:
      - ${VAULT_PORT}:${VAULT_PORT}
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
    volumes:
      - ./volumes/vault/logs:/vault/logs
      - ./volumes/vault/file:/vault/file
      - ./volumes/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl