version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    platform: linux/arm64/v8  # For M1/M2 Macs
    environment:
      POSTGRES_DB: propertymanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: amazoncorretto:17-alpine
    platform: linux/arm64/v8
    working_dir: /app
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/propertymanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: sh -c "./gradlew bootRun"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/api/properties"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    platform: linux/arm64/v8
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      backend:
        condition: service_healthy
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped

volumes:
  postgres_data:
  node_modules:
  gradle_cache: