version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    platform: linux/arm64/v8  # For M1/M2 Macs
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d propertydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    working_dir: /app
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/propertydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped

  postgres-test:
    image: postgres:14-alpine
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: propertymanager_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster test execution
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    image: amazoncorretto:17-alpine
    platform: linux/arm64/v8
    working_dir: /app
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: test
    command: sh -c "./gradlew test --info"

volumes:
  postgres_data:
  node_modules:
  gradle_cache: