version: '3.8'

services:
  test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["./gradlew", "test"]

  postgres-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=property_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" 