spring:
  application:
    name: propertyManager
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      token: ${VAULT_TOKEN}
      kv:
        enabled: false
      database:
        enabled: true
        role: readonly
        backend: database
      config:
        lifecycle:
          min-renewal: 30s
          expiry-threshold: 10s
  datasource:
    url: jdbc:postgresql://localhost:5444/${POSTGRES_DB}?currentSchema=public&user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}